version: '3.1'
services: 
 web:
    image: navidonskis/nginx-php5.6
    container_name: web
    restart: always
    depends_on: 
      - db
      - adminer
    volumes:
      - ../app/:/var/www
      - ./sites-enabled:/etc/nginx/sites-enabled
    ports: 
      - "80:80"
 db:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
    depends_on: 
      - adminer
 adminer:
    image: adminer
    restart: always
    ports: 
      - 8080:8080